### ISSUE TITLE
I already said, it's over

### ISSUE THREAD

**Issue by Milo123459** [sujalgoel/reddit-image#1]
It's annoying. Stop doing it.

**Comment by sujalgoel** [comment]
wait what? I am not doing anything.

**Comment by Milo123459** [comment]
Really? https://npm.im/@sujalgoel/reddit-image

**Comment by sujalgoel** [comment]
> Really? https://npm.im/@sujalgoel/reddit-image

I seriously don't know who is doing this and if i can do this then i will do it to all of my packages, not only to one. So, please try to understand.

**Comment by Milo123459** [comment]
> > Really? https://npm.im/@sujalgoel/reddit-image
> 
> 
> 
> I seriously don't know who is doing this and if i can do this then i will do it to all of my packages, not only to one. So, please try to understand.

Sure I understand but for the love of god stop changing the title
